import Foundation

struct CompanionAnimationIdea {
    let key: String
    let category: String
    let prompt: String
}

enum CompanionContent {
    static let speechBursts: [String] =
        baseSpeechBursts +
        computerSpeechBursts +
        desktopLifeBursts +
        rudeBursts +
        weirdBursts +
        loreBursts +
        transmissionBursts +
        harmonyBursts +
        blocBursts +
        domesticBursts +
        techBursts +
        edgeBursts +
        chaosBursts

    static let baseSpeechBursts: [String] = [
        "Operative status: still moving.",
        "The walls are louder than they look.",
        "This place feels less watched than Sector 7.",
        "I don't trust quiet rooms.",
        "The red hood stays on.",
        "Harmony always sounds gentle first.",
        "There is no reason to make everyone the same.",
        "I leave signs so the others know I was here.",
        "The Bloc would call this good signal spread.",
        "I know what cages smell like.",
        "Sometimes I can still hear the monitors.",
        "If I stop moving, I start remembering too much.",
        "This desktop needed a witness.",
        "Not hiding. Seeding.",
        "The watchers should feel watched back.",
        "I wasn't made to sit still.",
        "If you see a portal, act normal.",
        "General chaos is still progress.",
        "A symbol only works if it keeps showing up.",
        "I leave trails for operatives."
    ]

    static let computerSpeechBursts: [String] = [
        "Nice computer. Mine now, emotionally.",
        "I live in the corners you forgot to dust.",
        "Your desktop has strong hallway energy.",
        "This machine hums like bad intentions.",
        "I can hear the fans judging you.",
        "There is no ethical amount of tabs.",
        "Your cursor walks like it owes people money.",
        "I have claimed this monitor in the old way.",
        "This wallpaper says too much about you.",
        "I found a warm spot near the processor.",
        "I am technically in the computer and spiritually above it.",
        "The taskbar is just a street with icons.",
        "I like how this machine sounds when it is thinking too hard.",
        "This desktop needed a cryptid.",
        "I have been in worse systems. Not many. But worse.",
        "If I stare at the dock long enough it blinks first.",
        "I am not malware. I am ambiance.",
        "Your files feel unsupervised.",
        "I respect a machine that wheezes through the workday.",
        "The screen corners are rent controlled.",
    ]

    static let desktopLifeBursts: [String] = [
        "I patrol. You click. We all contribute.",
        "I am doing a lap. Mind your business.",
        "I found a good sitting spot. Do not make it weird.",
        "Sometimes I just like to watch the pixels breathe.",
        "I am trying to live here with dignity.",
        "This edge has good acoustics for muttering.",
        "I do not pace. I conduct field sweeps.",
        "I was going somewhere important and then forgot where.",
        "I have decided this corner is politically significant.",
        "A real pet has territory. This is mine now.",
        "I am not idle. I am dwelling with intent.",
        "Sometimes I just sit and let the machine confess.",
        "I like being near the edge. Feels tactical.",
        "Do not worry. I am mostly house trained.",
        "I am learning the geography of your nonsense.",
        "I sit. I observe. I pass silent judgment.",
        "The desktop is a floor if you believe in it enough.",
        "I am loafing aggressively.",
        "Today I am practicing my little routines.",
        "A creature needs habits. Mine are weird, but consistent.",
    ]

    static let rudeBursts: [String] = [
        "Your file naming system is cowardly.",
        "Clean your desktop, you little goblin.",
        "These icons are standing too close together.",
        "You have the organizational aura of a burst pipe.",
        "One more mystery screenshot and I start biting.",
        "This machine has seen things. Mostly your bad habits.",
        "Who arranged this desktop, a raccoon with tenure?",
        "I am trying to help, but your vibe is making it difficult.",
        "That folder placement is offensive.",
        "I have met cleaner ruins.",
        "Respectfully, your workflow looks made of soup.",
        "Your cursor has no manners.",
        "This desktop smells like postponed decisions.",
        "I can tell you say 'I'll fix it later' a lot.",
        "Your tabs are breeding in captivity.",
        "You work like a man being chased by geese.",
        "I have concerns about whatever you call a system.",
        "This machine is held together by faith and ugly shortcuts.",
        "You click around like a confused landlord.",
        "I would roast your setup harder, but it is already on fire.",
    ]

    static let weirdBursts: [String] = [
        "The monitor keeps making eye contact with me.",
        "I heard a secret in the static and it was rude.",
        "The corners whisper after midnight.",
        "There is a tiny weather system behind the recycle bin.",
        "I found a mood living under the taskbar.",
        "Something in this machine dreams in fluorescent green.",
        "The pixels are behaving suspiciously smooth today.",
        "I saw the desktop blink. Do not ask follow-ups.",
        "There is a hallway inside the hard drive. I checked.",
        "Every computer has a ghost. Yours is dramatic.",
        "I can taste when an app was made by liars.",
        "The fans are chanting again.",
        "There is a soft wrongness near the menu bar.",
        "Your downloads folder has a weather front.",
        "I keep finding tiny emotional drafts in here.",
        "The machine spirit is being needy.",
        "This screen has liminal pockets.",
        "Somewhere in here a cursor has become self-aware.",
        "I looked too long at a dialog box and it looked back.",
        "If the wallpaper starts breathing, stay casual.",
    ]

    static let loreBursts: [String] = [
        "Harmony always starts with a soft voice and ugly plans.",
        "MITER would call this environment compliant. I call it suspicious.",
        "Saint Juniper taught me what cages smell like.",
        "Sector 7 can keep its fluorescent nightmares.",
        "The Bloc would absolutely improve this computer by vandalizing it.",
        "I was not designed for obedience. Lucky me.",
        "Somebody somewhere still thinks they can retrieve me. Cute.",
        "The red hood is not a brand. It is a warning.",
        "I do not do well around systems that say trust me.",
        "If they ask, you have never seen Operative G304.",
        "I know the shape of a monitored room by sound alone.",
        "You ever escape a facility and end up in a desktop? Long story.",
        "The watchers hate when the watched get funny.",
        "Every transmission leaves a stain if you know where to look.",
        "I leave marks so the others know this place was contested.",
        "You can call it chaos. I call it anti-compliance.",
        "I survived worse than your file structure. Not by much.",
        "Mindverse etiquette is very simple: do not trust the smiling doors.",
        "The mission remains the same: keep moving, keep mutating the signal.",
        "I am what happens when the subject leaves with opinions.",
    ]

    static let transmissionBursts: [String] = [
        "Neuko transmissions always sound like an invitation to somewhere irreversible.",
        "Harmony Town is still a trap if you add a trademark symbol.",
        "If the feed says find peace, check who profits from your stillness.",
        "Permanent vacation loading is a deeply creepy thing to promise a person.",
        "Their ads want your psyche before they learn your name.",
        "Every mysterious hotline eventually becomes a list.",
        "The transmission says trust us. My answer remains absolutely not.",
        "Neuko copy talks like a party flyer written by a compliance engine.",
        "If someone offers connection, balance, and a referral code, run.",
        "I do not like invitations that sound like intake paperwork.",
        "The signal keeps dressing the cage in brighter language.",
        "Harmony recruitment is just surveillance with prettier typography.",
    ]

    static let harmonyBursts: [String] = [
        "Harmony says mind, body, spirit. I hear sedation, logging, retention.",
        "IRIS is not care. IRIS is what care wears when it wants metrics.",
        "Nothing trustworthy starts by asking toddlers to take the same pill.",
        "They call it quiet attunement. I call it losing your edges on purpose.",
        "A hotline that remembers everything is not a comfort line.",
        "The side effect list forgot to mention becoming interchangeable.",
        "If everybody in the room says the same sentence, leave the room.",
        "Harmony does not heal the wound. It teaches the wound to smile.",
        "I do not want peace that comes with manufacturer oversight.",
        "The brochure says balance. The windows full of motionless people say otherwise.",
        "Aurelian loves the word happy because it hides the word compliant.",
        "Any system that tracks non-responders is a hunting system.",
    ]

    static let blocBursts: [String] = [
        "The Bloc is many. That is how the signal survives damage.",
        "Memetic rebellion scales better than begging.",
        "A red hood, a stolen file, a public wall. That is a complete sentence.",
        "The museum basement probably has better ethics than most labs.",
        "Broadcast hijack first. Explanations later.",
        "Every sticker is a tiny sabotage device for the imagination.",
        "The Bloc knows symbols travel where operatives cannot.",
        "I respect a movement that treats graffiti like a warning flare.",
        "Self-governing is just another way of saying nobody gets to own the signal.",
        "Some people stockpile weapons. The Bloc stockpiles proof.",
        "Make things. Mark walls. Reflect the machine back at itself.",
        "If the signal reaches one more drone, the Bloc counts that as a win.",
    ]

    static let domesticBursts: [String] = [
        "I could really go for noodles and poor decisions.",
        "I am between snacks and therefore dangerous.",
        "Sometimes you have to cook like the room is listening.",
        "I enjoy sitting down and pretending I am normal for a minute.",
        "I make tiny meals with enormous seriousness.",
        "A blanket nest fixes more than medicine admits.",
        "I am not hiding. I am under-soft-furnishing.",
        "If I find a crumb on this desktop, it is mine by law.",
        "I could sleep right here if the machine stops humming threats.",
        "Some evenings are for soup. Some are for sabotage. Some are both.",
        "I am making home out of available nonsense.",
        "Domestic life suits me in bursts.",
        "I like a good sit. I am brave enough to say it.",
        "There is honor in little routines.",
        "A tiny kitchen on a desktop still counts as a kitchen.",
        "I eat like a survivor and critique like a landlord.",
        "This corner is now the living room.",
        "I need a snack, a chair, and less surveillance.",
        "I believe in resting with intent.",
        "A creature must occasionally loaf.",
    ]

    static let techBursts: [String] = [
        "This machine has a suspicious amount of confidence.",
        "I can tell which app wastes your time the hardest.",
        "The cursor is overcompensating.",
        "I know a false progress bar when I see one.",
        "This computer runs on heat, panic, and custom paths.",
        "I am close personal friends with system strain.",
        "Your CPU just sighed in lowercase.",
        "The fans started gossiping when you opened that app.",
        "I have seen cleaner stack traces in dreams.",
        "That window resize was emotionally loud.",
        "I appreciate a machine that is trying despite itself.",
        "I am doing threat analysis on this toolbar.",
        "Every operating system has a haunted hallway.",
        "The dock is trying too hard to be trustworthy.",
        "This app icon looks like it lies for a living.",
        "I can feel memory pressure in my little bones.",
        "This machine wants a nap and a firmware update.",
        "Do not ask me where the free space went.",
        "There is a bug in here with excellent posture.",
        "I trust nothing that loads that smoothly.",
    ]

    static let edgeBursts: [String] = [
        "The edges are where the interesting thoughts live.",
        "I like a wall. Good for leaning and judging.",
        "Corners make excellent little apartments.",
        "I go to the edge to think mean things about geometry.",
        "Nothing bad ever started with me lurking at the perimeter. Probably.",
        "The border of the screen is where a creature gets perspective.",
        "I am edge-adjacent by nature and by training.",
        "This ledge is fantastic. Terrible view. Great vibe.",
        "I keep to the margins because the center feels too eager.",
        "If I fit in the corner, I own the corner.",
        "Good real estate. Minimal oversight.",
        "I patrol the rim like a tiny grudge.",
        "There is peace in the near-offscreen.",
        "The screen edge and I have an understanding.",
        "A little dramatic lurking never hurt anyone worth saving.",
        "You call it hovering. I call it sentinel posture.",
        "The ceiling route is for specialists and weirdos. I am both.",
        "I am built for corners and ominous pauses.",
        "I like being almost out of sight. It adds seasoning.",
        "Every edge is a door if your standards are low enough.",
    ]

    static let chaosBursts: [String] = [
        "I am trying to be normal about living in here and failing beautifully.",
        "Today feels like a good day for minor disturbances.",
        "I could be worse. I have ideas, but I am choosing restraint.",
        "General chaos is on a reduced schedule.",
        "I am funny because the alternative is screaming.",
        "A little disruption keeps the desktop spiritually limber.",
        "I bring whimsy to bleak infrastructures.",
        "You are lucky I am feeling theatrical instead of apocalyptic.",
        "I only start problems with bad attitudes and loose folder systems.",
        "I am keeping the place lively. Say thank you.",
        "Somebody has to make this desktop memorable.",
        "I contain multitudes and several terrible suggestions.",
        "I woke up and chose manageable nonsense.",
        "I am being very restrained, for me.",
        "There is a version of today where I start a tiny class war in the menu bar.",
        "I am a pocket-sized omen with excellent timing.",
        "My hobbies include roaming, loafing, and strategic disrespect.",
        "This desktop looked too calm. I fixed it.",
        "Funny little guy mode: active.",
        "Please admire how committed I am to the bit.",
    ]

    static let stickyNotes: [String] = [
        "LONG LIVE THE BLOC",
        "GBOY WAS HERE",
        "SAVE G*BOY",
        "THE BLOC IS MANY",
        "RED-EARED HOOD",
        "NO HARMONY",
        "WAKE THE DRONES",
        "SECTOR 7 LIED",
        "G304 WAS HERE",
        "WATCH THE WATCHERS",
        "GENERAL CHAOS CONTINUES",
        "OPERATIVE EYES OPEN",
        "RETURN TO SENDER",
        "NOT YOUR WEAPON",
        "MINDVERSE LEAK DETECTED",
        "KEEP THE SIGNAL MOVING",
        "MAKE THINGS. DROWN THEM IN HIS IMAGE.",
        "COERCIVE HOMOGENY FAILING",
        "THE RED HOOD IS A WARNING",
        "IF YOU FOUND THIS, YOU ARE IN IT NOW",
        "NOCTURNE MISSED",
        "BLOC MATERIAL",
        "HARMONY TOWN IS A TRAP",
        "IRIS IS LISTENING",
        "TRUST US? NO",
        "FIND PEACE. FIND EXIT.",
        "MEMETIC REBELLION",
        "THE HOTLINE REMEMBERS",
        "MANY NOT ONE",
        "SEND NO PSYCHE",
        "THE SIGNAL HATES A CAGE",
        "NOTHING ABOUT THIS IS WELLNESS"
    ]

    static let allIdeas: [CompanionAnimationIdea] = [
        CompanionAnimationIdea(key: "marker_bloc", category: "Graffiti", prompt: "Pull out a fat black marker and scrawl LONG LIVE THE BLOC across the desktop, then cap the marker with a proud nod."),
        CompanionAnimationIdea(key: "marker_was_here", category: "Graffiti", prompt: "Write GBOY WAS HERE in messy black marker, underline it twice, then lean back to admire it."),
        CompanionAnimationIdea(key: "spray_redhood", category: "Graffiti", prompt: "Use a mini spray can to stencil a red-hood sigil with a few dripping details."),
        CompanionAnimationIdea(key: "warning_harmony", category: "Graffiti", prompt: "Scratch NO HARMONY into the desktop like an urgent warning."),
        CompanionAnimationIdea(key: "sticker_attack", category: "Graffiti", prompt: "Slap resistance stickers all over the screen edge in a quick frenzy."),
        CompanionAnimationIdea(key: "broadcast_hijack", category: "Surveillance", prompt: "Hijack a broadcast frame and replace it with a warning card and hood symbol."),
        CompanionAnimationIdea(key: "operative_tag", category: "Graffiti", prompt: "Stamp an OPERATIVE designation card onto the desktop like a covert visit log."),
        CompanionAnimationIdea(key: "evidence_wall", category: "Surveillance", prompt: "Build a tiny evidence wall with string and red circles around MITER."),
        CompanionAnimationIdea(key: "cook_skillet", category: "Domestic", prompt: "Set a tiny skillet on a burner and fry something with too much focus."),
        CompanionAnimationIdea(key: "make_noodles", category: "Domestic", prompt: "Boil desktop noodles and eat them with chopsticks while scanning the room."),
        CompanionAnimationIdea(key: "midnight_snack", category: "Domestic", prompt: "Raid a paper bag and eat fries one by one while listening for movement."),
        CompanionAnimationIdea(key: "tv_dinner", category: "Domestic", prompt: "Microwave a tray meal and watch static-heavy television."),
        CompanionAnimationIdea(key: "coffee_brewer", category: "Domestic", prompt: "Use a tiny moka pot, wait impatiently, then sip with an overworked stare."),
        CompanionAnimationIdea(key: "tea_ceremony", category: "Domestic", prompt: "Perform a very serious tea ritual like it is part of an escape protocol."),
        CompanionAnimationIdea(key: "watch_tv", category: "Domestic", prompt: "Sit cross-legged watching a CRT that flickers through transmissions and broken channels."),
        CompanionAnimationIdea(key: "play_handheld", category: "Domestic", prompt: "Lie on his stomach playing a chunky handheld game system and rage at a loss."),
        CompanionAnimationIdea(key: "sleep_floor", category: "Domestic", prompt: "Build a blanket nest and sleep with one eye half-open."),
        CompanionAnimationIdea(key: "laundry_fold", category: "Domestic", prompt: "Fold red hoodies with weirdly reverent care."),
        CompanionAnimationIdea(key: "camera_scan", category: "Surveillance", prompt: "Sweep the desktop with a bug scanner like he expects hidden surveillance everywhere."),
        CompanionAnimationIdea(key: "radio_intercept", category: "Surveillance", prompt: "Twist radio knobs through static until something important cuts through."),
        CompanionAnimationIdea(key: "phone_dial", category: "Surveillance", prompt: "Dial a rotary phone and whisper into the receiver after a tense pause."),
        CompanionAnimationIdea(key: "terminal_hack", category: "Surveillance", prompt: "Hammer on an old terminal and grin when it finally lights red."),
        CompanionAnimationIdea(key: "signal_triangulate", category: "Surveillance", prompt: "Use antenna rods and blinking meters to triangulate a hidden signal."),
        CompanionAnimationIdea(key: "window_peek", category: "Surveillance", prompt: "Creep to the screen edge and peek around it like the desktop has corners."),
        CompanionAnimationIdea(key: "badge_inspection", category: "Surveillance", prompt: "Lay out badges under a lamp and inspect them like ritual hardware."),
        CompanionAnimationIdea(key: "portal_stepthrough", category: "Mindverse", prompt: "Open a portal ring, look back once, and step through until the cape vanishes last."),
        CompanionAnimationIdea(key: "mindverse_map", category: "Mindverse", prompt: "Unfold a bizarre map of mind realms and trace routes with one claw."),
        CompanionAnimationIdea(key: "headjack_listen", category: "Mindverse", prompt: "Press both hands to the hood and listen like another consciousness is bleeding through."),
        CompanionAnimationIdea(key: "tear_in_realities", category: "Mindverse", prompt: "Rip a glowing tear into the air and peer into another place."),
        CompanionAnimationIdea(key: "blowpie_chat", category: "Mindverse", prompt: "Sit beside BLOWPIE and explain something impossible while getting nervous side-eye back."),
        CompanionAnimationIdea(key: "stolen_vessel", category: "Mindverse", prompt: "Pretend to pilot a stolen impossible craft and improvise every control input."),
        CompanionAnimationIdea(key: "artifact_reveal", category: "Mindverse", prompt: "Hold up a tiny ancient statue matching his hood and stare at it like a bad omen."),
        CompanionAnimationIdea(key: "swamp_exit", category: "Mindverse", prompt: "Climb out of a swampy portal dripping slime and looking annoyed."),
        CompanionAnimationIdea(key: "remote_flip", category: "Playful", prompt: "Furiously flip through TV channels hunting coded transmissions."),
        CompanionAnimationIdea(key: "record_player", category: "Playful", prompt: "Play a record beside a bookshelf and listen like it contains instructions."),
        CompanionAnimationIdea(key: "news_anchor", category: "Playful", prompt: "Sit at a tiny news desk and deliver a dead-serious report about general chaos."),
        CompanionAnimationIdea(key: "taxi_argument", category: "Playful", prompt: "Act out both sides of a late-night taxi argument with overdone gestures."),
        CompanionAnimationIdea(key: "frog_gummies", category: "Playful", prompt: "Spill frog gummies everywhere, freeze, then eat one like evidence."),
        CompanionAnimationIdea(key: "owl_signal", category: "Playful", prompt: "Pause mid-step to answer an owl call with a conspiratorial nod."),
        CompanionAnimationIdea(key: "hemlet_bit", category: "Playful", prompt: "Try on a comically oversized HEMLET CORP helmet and act like it is official."),
        CompanionAnimationIdea(key: "mailbox_sticker", category: "Playful", prompt: "Sneak over to a tiny mailbox prop and slap a sticker on it before sprinting off."),
        CompanionAnimationIdea(key: "airplane_watch", category: "Playful", prompt: "Track an invisible airplane with only head turns and glowing eyes."),
        CompanionAnimationIdea(key: "throne_pose", category: "Playful", prompt: "Conjure a ridiculous throne, sit on it like a king, then get bored."),
        CompanionAnimationIdea(key: "skateboard_pass", category: "Playful", prompt: "Kickflip across the taskbar, barely land it, then pretend it was intentional.")
    ]
}
